export const CREATE_TEAM_REQUEST = "@@teams/CREATE_TEAM_REQUEST";
export const CREATE_TEAM_SUCCESS = "@@teams/CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_FAILURE = "@@teams/CREATE_TEAM_FAILURE";

export const FETCH_TEAM_REQUEST = "@@teams/FETCH_TEAM_REQUEST";
export const FETCH_TEAM_SUCCESS = "@@teams/FETCH_TEAM_SUCCESS";
export const FETCH_TEAM_FAILURE = "@@teams/FETCH_TEAM_FAILURE";

export const FETCH_TEAM_SCRIM_REQUEST = "@@teams/FETCH_TEAM_SCRIM_REQUEST"
export const FETCH_TEAM_SCRIM_SUCCESS = "@@teams/FETCH_TEAM_SCRIM_SUCCESS"
export const FETCH_TEAM_SCRIM_FAILURE = "@@teams/FETCH_TEAM_SCRIM_FAILURE"
