export const INVITE_TEAM_USER_REQUEST = "@@notifications/INVITE_TEAM_USER_REQUEST";
export const INVITE_TEAM_USER_SUCCESS = "@@notifications/INVITE_TEAM_USER_SUCCESS";
export const INVITE_TEAM_USER_FAILURE = "@@notifications/INVITE_TEAM_USER_FAILURE";

export const GENERATE_TEAM_INVITE_LINK_REQUEST = "@@notifications/GENERATE_TEAM_INVITE_LINK_REQUEST";
export const GENERATE_TEAM_INVITE_LINK_SUCCESS = "@@notifications/GENERATE_TEAM_INVITE_LINK_SUCCESS";
export const GENERATE_TEAM_INVITE_LINK_FAILURE = "@@notifications/GENERATE_TEAM_INVITE_LINK_FAILURE";

export const INVITATION_DETAIL_REQUEST = "@@notifications/INVITATION_DETAIL_REQUEST";
export const INVITATION_DETAIL_SUCCESS = "@@notifications/INVITATION_DETAIL_SUCCESS";
export const INVITATION_DETAIL_FAILURE = "@@notifications/INVITATION_DETAIL_FAILURE";

export const ACCEPT_INVITATION_REQUEST = "@@notifications/ACCEPT_INVITATION_REQUEST";
export const ACCEPT_INVITATION_SUCCESS = "@@notifications/ACCEPT_INVITATION_SUCCESS";
export const ACCEPT_INVITATION_FAILURE = "@@notifications/ACCEPT_INVITATION_FAILURE";
