export const USER_INFO_REQUEST = '@@user/USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = '@@user/USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = '@@user/USER_INFO_FAILURE';

export const SET_ACTIVE_TEAM_START = '@@user/SET_ACTIVE_TEAM_START';
export const SET_ACTIVE_TEAM_REQUEST = '@@user/SET_ACTIVE_TEAM_REQUEST';
export const SET_ACTIVE_TEAM_SUCCESS = '@@user/SET_ACTIVE_TEAM_SUCCESS';
export const SET_ACTIVE_TEAM_FAILURE = '@@user/SET_ACTIVE_TEAM_FAILURE';

export const CHANGE_ACTIVE_TEAM_REQUEST = '@@user/CHANGE_ACTIVE_TEAM_REQUEST';
export const CHANGE_ACTIVE_TEAM_SUCCESS = '@@user/CHANGE_ACTIVE_TEAM_SUCCESS';
export const CHANGE_ACTIVE_TEAM_FAILURE = '@@user/CHANGE_ACTIVE_TEAM_FAILURE';

export const FETCH_USER_TEAM_PERMISSIONS_REQUEST = "@@user/FETCH_USER_TEAM_PERMISSIONS_REQUEST";
export const FETCH_USER_TEAM_PERMISSIONS_SUCCESS = "@@user/FETCH_USER_TEAM_PERMISSIONS_SUCCESS";
export const FETCH_USER_TEAM_PERMISSIONS_FAILURE = "@@user/FETCH_USER_TEAM_PERMISSIONS_FAILURE";
