export const DELETE_TEAM_ROLE_REQUEST = "@@teamSettings/DELETE_TEAM_ROLE_REQUEST";
export const DELETE_TEAM_ROLE_SUCCESS = "@@teamSettings/DELETE_TEAM_ROLE_SUCCESS";
export const DELETE_TEAM_ROLE_FAILURE = "@@teamSettings/DELETE_TEAM_ROLE_FAILURE";

export const FETCH_TEAM_SETTINGS_REQUEST = "@@teamSettings/FETCH_TEAM_SETTINGS_REQUEST";
export const FETCH_TEAM_SETTINGS_SUCCESS = "@@teamSettings/FETCH_TEAM_SETTINGS_SUCCESS";
export const FETCH_TEAM_SETTINGS_FAILURE = "@@teamSettings/FETCH_TEAM_SETTINGS_FAILURE";

export const SET_TEAM_LOGO_REQUEST = "@@teamSettings/SET_TEAM_LOGO_REQUEST";
export const SET_TEAM_LOGO_SUCCESS = "@@teamSettings/SET_TEAM_LOGO_SUCCESS";
export const SET_TEAM_LOGO_FAILURE = "@@teamSettings/SET_TEAM_LOGO_FAILURE";

export const SET_TEAM_SETTINGS_REQUEST = "@@teamSettings/SET_TEAM_SETTINGS_REQUEST";
export const SET_TEAM_SETTINGS_SUCCESS = "@@teamSettings/SET_TEAM_SETTINGS_SUCCESS";
export const SET_TEAM_SETTINGS_FAILURE = "@@teamData/SET_TEAM_SETTINGS_FAILURE";
