export const TEAM_VIEW_INFO_REQUEST = '@@teamView/TEAM_VIEW_INFO_REQUEST';
export const TEAM_VIEW_INFO_SUCCESS = '@@teamView/TEAM_VIEW_INFO_SUCCESS';
export const TEAM_VIEW_INFO_FAILURE = '@@teamView/TEAM_VIEW_INFO_FAILURE';

export const TEAM_VIEW_SCRIMS_REQUEST = '@@teamView/TEAM_VIEW_SCRIMS_REQUEST';
export const TEAM_VIEW_SCRIMS_SUCCESS = '@@teamView/TEAM_VIEW_SCRIMS_SUCCESS';
export const TEAM_VIEW_SCRIMS_FAILURE = '@@teamView/TEAM_VIEW_SCRIMS_FAILURE';
